### ISSUE TITLE
[Error] Class constructor Record cannot be invoked without 'new'

### ISSUE THREAD

**Issue by DevilsNightsix** [alexeyraspopov/dataclass#1]
Hi, i tried to use your lib in my angular4(ts) project. And I faced problem.
I defined my model as
```typescript
import Record from 'dataclass';

export default class User extends Record<User> {
  id: number = 0;
  firstName: string = '';
  lastName: string = '';
  email: string = '';
  username: string = '';
}
```
And trying to use it this way
```typescript
import User from '../models/User';

let user = new User(action.payload.session.user);
```

And getting
```
TypeError: Class constructor Record cannot be invoked without 'new' at new User
```

**Comment by alexeyraspopov** [comment]
Hi @DevilsNightsix. Thank you for you submission.

Unfortunately, I wasn't able to reproduce your case. What's the TypeScript version do you use?

I've encountered the issue with module exports and will try to fix it asap.

**Comment by alexeyraspopov** [comment]
@DevilsNightsix, I've published `v1.0.1` with a small fix for modules interoperability. You can try to use it.

**Comment by alexeyraspopov** [comment]
Besides TypeScript version, what are the `module` and `target` configurations do you use?

**Comment by DevilsNightsix** [comment]
@alexeyraspopov My configuration is `module: "es2015"`, `target: 'es5'` and typescript version is 2.3.3

*UPD*: Updating solved the issue. Thanks for fast answer.

**Comment by alexeyraspopov** [comment]
Will try to create additional tests for TypeScript to prevent such cases.

Thanks for reporting.
