### ISSUE TITLE
Nested dataclasses are either not supported or undocumented

### ISSUE THREAD

**Issue by olafur-palsson** [alexeyraspopov/dataclass#12]
I like your library, I'm thinking about how to implemented a nested Record

```ts
// I'm interested in something like this:
class Something extends Record<Something> {
  message: string
  timestamp: string
}

class User extends Record<User> {
  id: string
  something: Something
}
```

It is either undocumented or unsupported though.

**Comment by alexeyraspopov** [comment]
The support for this was added in https://github.com/alexeyraspopov/dataclass/commit/d3b93271ba28fa9389a14b3947b606928d4f2ef1 and available in latest version (`v1.2.0`). I updated the docs to mention the possibility in https://github.com/alexeyraspopov/dataclass/commit/7d72ecc3f048be8152c5846a2dcfc5d3188dadda.

> I'd like to apologize for the fact that my absence may affect your experience in using the project and I appreciate if you found it useful regardless. I'll be committing more time to improve the docs and examples in nearest future. ✌️
