### ISSUE TITLE
Document parameter properties as a partial alternative

### ISSUE THREAD

**Issue by johnthagen** [alexeyraspopov/dataclass#13]
[Parameter properties](https://www.typescriptlang.org/docs/handbook/classes.html#parameter-properties) reduce some of the boilerplate associated with TypeScript classes.

They can be used to change:

```typescript
class Octopus {
  private legs;
  private numberOfLegs;
  constructor(name: string, numberOfLegs: number) {
    this.name = name;
    this.numberOfLegs = numberOfLegs;
  }
}
```

To:

```typescript
class Octopus {
  constructor(private name: string, private numberOfLegs: number) {}
}
```

Which partially addresses some of the boilerplate issues related to TypeScript `class`es.

**Comment by alexeyraspopov** [comment]
I believe this issue is properly addressed in v2.0.0 since there is no need to use generic syntax

```ts
import { Data } from "dataclass";

class Octopus extends Data {
  name: string = "Octo";
  numberOfLegs: number = 8;
}

let octo = Octopus.create({ name: "Octavius" });
// > Octopus { name: "Octavius", numberOfLegs: 8 }
```

I can't make much ose of parameter properties since it's primarily a TS feature.
