### ISSUE TITLE
can you publish a new version?

### ISSUE THREAD

**Issue by mingchuno** [alexeyraspopov/dataclass#5]
Since there is quite some update since the last release (v1.1.1). Will there be a new version published? @alexeyraspopov

**Comment by alexeyraspopov** [comment]
Nothing really changed in the source code after v1.1.1 was released. I've been working on updating docs and attempting to make complete website.

I'm experimenting with slightly different algorithm under the hood. Not sure where it can be done or make some real difference.

Is there any specific issue you want to tackle with a new release? Version 1.1.1 should work as described in the latest docs.

**Comment by mingchuno** [comment]
Not really. Thx for your prompt reply! @alexeyraspopov
